export const homeObjThree = {
  id: "projects",
  lightBg: true,
  lightText: false,
  buttonLabel: "See More Projects",
  heading: "My projects",
  icon1: require("../../../images/project-1.svg").default,
  heading1: "Autonomous Systems",
  text1: "Master's Thesis Project.",
  icon2: require("../../../images/project-2.svg").default,
  heading2: "Musicorum",
  text2: "A Music web application.",
  icon3: require("../../../images/project-3.svg").default,
  heading3: "Latifa's Web",
  text3: "Personal website.",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "blog",
  lightBg: false,
  lightText: true,
  buttonLabel: "See More Posts",
  heading: "My blogs",
  icon1: require("../../../images/blog-1.svg").default,
  heading1: "(IoT) (SIoT)",
  text1: "What changed from Ubiquitous Computing to the Social Internet of Things (SIoT)",
  icon2: require("../../../images/blog-2.svg").default,
  heading2: "(IoT) (Proxemics)",
  text2: "The application of Proxemics in Internet of Things",
  icon3: require("../../../images/blog-3.svg").default,
  heading3: "(IoT) (Robotics) (HRI)",
  text3: "The role of Emotions in Human-Robot Interaction (HRI)",
  dark: true,
  primary: true,
  darkText: false,
};
